name: some-axum-code

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

volumes:
  postgres-data:
    driver: local
